version: '3.3'

services:
   spring-monitor:
      build:
        context: .
        dockerfile: Dockerfile
      image: spring-monitor
      ports:
        - 7771:7771
      networks:
        - network1
networks:
  network1:
